name: Run Firmware in QEMU
on: push
jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install QEMU and ARM GCC Toolchain
        run: sudo apt update && sudo apt install -y qemu-system-arm gcc-arm-none-eabi make

      - name: Verify Repository Structure
        run: |
          echo "Checking repository structure..."
          ls -la
          if [ ! -d "firmware" ]; then 
            echo "❌ ERROR: 'firmware/' directory is missing!"; 
            exit 1; 
          fi

      - name: Build Firmware
        run: |
          cd firmware
          if [ -f "Makefile" ]; then 
            make
          else 
            echo "❌ ERROR: Makefile is missing in firmware directory!"
            exit 1
          fi

      - name: Run Firmware in QEMU
        run: qemu-system-arm -M stm32f103c8 -kernel firmware/firmware.elf -serial stdio


     
