name: Run Firmware in QEMU
on: push
jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install QEMU
        run: sudo apt update && sudo apt install -y qemu-system-arm
      - name: Build Firmware
        run: |
          sudo apt install -y gcc-arm-none-eabi make
          cd firmware && make
      - name: Run Firmware
        run: qemu-system-arm -M stm32f103c8 -kernel firmware/firmware.elf -serial stdio


